### ISSUE TITLE
Error on sending email

### ISSUE THREAD

**Issue by GuguRD** [gunnery/gunnery#49]
Even after I setup google SMTP or AWS SMS i got this error:

```
Traceback (most recent call last):
  File "/root/.virtualenvs/dev_webdeploy2/local/lib/python2.7/site-packages/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.virtualenvs/dev_webdeploy2/local/lib/python2.7/site-packages/celery/app/trace.py", line 416, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/repos/webdeploy2/backend/tasks.py", line 274, in run
    message.send()
  File "/root/.virtualenvs/dev_webdeploy2/local/lib/python2.7/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/root/.virtualenvs/dev_webdeploy2/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "/root/.virtualenvs/dev_webdeploy2/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 51, in open
    self.connection.starttls()
  File "/usr/lib/python2.7/smtplib.py", line 644, in starttls
    raise SMTPException("STARTTLS extension not supported by server.")
SMTPException: STARTTLS extension not supported by server.
```

**Comment by GuguRD** [comment]
Fixed it by upgrading paramiko
